
# Site settings
title: zzyw
email: hi@zzywstudio.com
# description: "zzyw is a new york based design & technology studio"
baseurl: "/workshop" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
author: zzyw


# Build settings
markdown: kramdown


collections:
- exhibitions
